name: q1zZ-DiscordRewards
main: me.q1zz.discordrewards.DiscordRewardsPlugin
version: 0.6
description: Simple plugin for receiving reward for join to discord server.
website: https://github.com/q1zZu
softdepend: [PlaceholderAPI]
commands:
  dcReload:
    aliases: [discordReload, discordRewardsReload, q1zz-reload, q1zzReload]
